// This is a Zig version of a raylib example from
// https://github.com/raysan5/raylib/
// It is distributed under the same license as the original - unmodified zlib/libpng license
// Header from the original source code follows below:

///*******************************************************************************************
//*
//*   raylib [shapes] example - draw circle sector (with gui options)
//*
//*   Example originally created with raylib 2.5, last time updated with raylib 2.5
//*
//*   Example contributed by Vlad Adrian (@demizdor) and reviewed by Ramon Santamaria (@raysan5)
//*
//*   Example licensed under an unmodified zlib/libpng license, which is an OSI-certified,
//*   BSD-like license that allows static linking with closed source software
//*
//*   Copyright (c) 2018-2023 Vlad Adrian (@demizdor) and Ramon Santamaria (@raysan5)
//*
//********************************************************************************************/


// Download raygui.h from https://github.com/raysan5/raygui/tree/master/src and copy it to this project's folder.
// Build with `zig build-exe main.zig -idirafter ./ -lc -lraylib`

// WARNING: unless this bug in Zig transtale - https://github.com/ziglang/zig/issues/15408 - has been fixed,
// you're going to see this error:

// /home/archie/.cache/zig/o/acc023fd58b4b17daf3bfe1b7f6e6bf2/cimport.zig:7620:27: error: incompatible types: 'c_int' and 'f32'
//                     value += (GetMouseDelta().y / (scrollbar.height - slider.height)) * @intToFloat(f32, valueRange);
//                     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// /home/archie/.cache/zig/o/acc023fd58b4b17daf3bfe1b7f6e6bf2/cimport.zig:7620:21: note: type 'c_int' here
//                     value += (GetMouseDelta().y / (scrollbar.height - slider.height)) * @intToFloat(f32, valueRange);
//                     ^~~~~
// /home/archie/.cache/zig/o/acc023fd58b4b17daf3bfe1b7f6e6bf2/cimport.zig:7620:87: note: type 'f32' here
//                     value += (GetMouseDelta().y / (scrollbar.height - slider.height)) * @intToFloat(f32, valueRange);
//                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// Zig incorrectly skips type coercion when translating certain C code in raygui.h.
// As a workaround edit the line in cimport.zig mentioned in the error message, manually adding necessary type coercion:
// value += @floatToInt(c_int, (GetMouseDelta().y / (scrollbar.height - slider.height)) * @intToFloat(f32, valueRange));
//
// Also correct the line below it:
// value += (GetMouseDelta().x / (scrollbar.width - slider.width)) * @intToFloat(f32, valueRange);
// Add similar type coercion:
// value += @floatToInt(c_int, (GetMouseDelta().x / (scrollbar.width - slider.width)) * @intToFloat(f32, valueRange));
//
// Yet another, similar code snippet was added in recent versions of raygui.h, leading to more of the same error,
// apply the same modification to each line where it is needed.
//
// Save cimport.zig and build the project again, it should compile without errors.

// You may need to do this again, if cimport.zig is regenerated by Zig :(

const c = @cImport(
{
    @cInclude("raylib.h");
    @cDefine("RAYGUI_IMPLEMENTATION", {});
    @cInclude("raygui.h"); // Required for GUI controls
});

pub fn main() void
{
    const screen_width = 800;
    const screen_height = 450;

    c.InitWindow(screen_width, screen_height, "raylib [shapes] example - draw circle sector");
    defer c.CloseWindow(); // Close window and OpenGL context

    const center = c.Vector2{ .x = @intToFloat(f32, c.GetScreenWidth() - 300) / 2.0, .y = @intToFloat(f32, c.GetScreenHeight()) / 2.0 };

    var outer_radius: f32 = 180.0;
    var start_angle: f32 = 0.0;
    var end_angle: f32 = 180.0;
    var segments: i32 = 0;
    var min_segments: i32 = 4;

    c.SetTargetFPS(60);

    while (!c.WindowShouldClose()) // Detect window close button or ESC key
    {
        // Update
        //----------------------------------------------------------------------------------
        // NOTE: All variables update happens inside GUI control functions
        //----------------------------------------------------------------------------------

        // Draw
        //---------------------------------------------------------------------------------
        c.BeginDrawing();
        defer c.EndDrawing();

        c.ClearBackground(c.RAYWHITE);

        c.DrawLine(500, 0, 500, c.GetScreenHeight(), c.Fade(c.LIGHTGRAY, 0.6));
        c.DrawRectangle(500, 0, c.GetScreenWidth() - 500, c.GetScreenHeight(), c.Fade(c.LIGHTGRAY, 0.3));

        c.DrawCircleSector(center, outer_radius, start_angle, end_angle, segments, c.Fade(c.MAROON, 0.3));
        c.DrawCircleSectorLines(center, outer_radius, start_angle, end_angle, segments, c.Fade(c.MAROON, 0.6));

        // Draw GUI controls
        //------------------------------------------------------------------------------
        start_angle = c.GuiSliderBar(.{ .x = 600.0, .y = 40.0, .width = 120.0, .height = 20.0 },
                                     "StartAngle", null, start_angle, 0.0, 720.0);
        end_angle = c.GuiSliderBar(.{ .x = 600.0, .y = 70.0, .width = 120.0, .height = 20.0 },
                                   "EndAngle", null, end_angle, 0.0, 720.0);

        outer_radius = c.GuiSliderBar(.{ .x = 600.0, .y = 140.0, .width = 120.0, .height = 20.0 },
                                      "Radius", null, outer_radius, 0.0, 200.0);
        segments = @floatToInt(i32, c.GuiSliderBar(.{ .x = 600.0, .y = 170.0, .width = 120.0, .height = 20.0 },
                                                   "Segments", null, @intToFloat(f32, segments), 0.0, 100.0));
        //------------------------------------------------------------------------------

        min_segments = @floatToInt(i32, @ceil((end_angle - start_angle) / 90.0));
        c.DrawText(c.TextFormat("MODE: %s", @ptrCast([*c]const u8, if (segments >= min_segments) "MANUAL" else "AUTO")),
                   600, 200, 10, if (segments >= min_segments) c.MAROON else c.DARKGRAY);
        c.DrawFPS(10, 10);
        //---------------------------------------------------------------------------------
    }
}
